version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - 8085:8085
    depends_on:
      - database
  database:
    image: library/postgres:13.0-alpine
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: android
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: android
    volumes:
      - ./database/data:/var/lib/postgresql/data